/*
 * generated by Xtext 2.9.0.rc2
 */
package org.xtext.example.mydsl.validation

import org.xtext.example.mydsl.myDsl.Component
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyDslValidator extends AbstractMyDslValidator {
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
//	def checkExistingFacetList(ComponentProperties cp)
//	{
//		for(it : cp.optionalProperties.filter(FacetList))
//		{
//			if(!Character.isUpperCase(it.name.toString.charAt(0)))
////			{
//				warning('mochkila',MyDslPackage.Literals.CHILDREN_PROPERTY);
//				System.out.println("MOCHKILA !!!"+it.name);
//			}
//		}
//	}
	@Check(NORMAL)
	def checkExistingFacetList(Component c)
	{
		System.out.println("HAAAAAAAAAAAAAAAAAAAA!!!!!!!!!");
		if(!Character.isUpperCase(c.getName().charAt(0)))
		{
			error("mochkila",null);
			System.out.println("MOCHKILA !!!"+c.getName());
		}
	}
	
	
}
